build:
  python: 3.10
  dependencies:
  - ecmwf/ecbuild@develop
  - MathisRosenhauer/libaec@refs/tags/v1.1.3
  - ecmwf/eccodes@develop
  - ecmwf/eckit@develop
  - ecmwf/mir@develop
  parallel: 1
  pytest_cmd: |
    FINDLIBS_DISABLE_PACKAGE=no pytest --cov=./ --cov-report=xml
    FINDLIBS_DISABLE_PACKAGE=no python -m coverage report
