# (C) Copyright 2023 ECMWF.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.


from ..utils import create_grid_object
from .grid import get_grid


def regrid_generic_field(field, index, in_grid=None, out_grid=None, backend=None, **kwargs):
    """Regrid a non-GRIB ``earthkit.data`` field via array-based interpolation.

    Parameters
    ----------
    field : earthkit.data.Field
        The field to regrid.
    index : int
        Position of ``field`` in its parent :class:`~earthkit.data.FieldList`, used
        only for error/log messages.
    in_grid : eckit.geo.Grid or earthkit.geo.grids.Grid, optional
        Input grid. When not provided it is determined from ``field``'s metadata.
    out_grid : eckit.geo.Grid or earthkit.geo.grids.Grid
        Output grid. Must be provided.
    backend : object
        Regrid backend exposing a ``regrid(values, in_grid, out_grid, **kwargs)`` method.
    **kwargs : dict
        Additional keyword arguments passed to ``backend.regrid``.

    Returns
    -------
    earthkit.data.Field
        A new field with the regridded values and updated grid spec.

    Raises
    ------
    ValueError
        If ``in_grid`` cannot be determined, ``out_grid`` is not provided, or the
        backend produces an invalid output grid.
    """
    if in_grid is None:
        in_grid = get_grid(field, index)

    if in_grid is None:
        raise ValueError(
            "Input grid could not be determined from data. Provide an explicit input grid via the 'in_grid' parameter."
        )

    assert out_grid is not None, "Output grid must be provided"

    vv = field.to_numpy(flatten=True)

    v_res, out_grid = backend.regrid(
        vv,
        in_grid,
        out_grid,
        **kwargs,
    )

    out_grid = create_grid_object(out_grid)
    if out_grid is None:
        raise ValueError("Invalid output grid generated by the regrid operation")

    return field.set({"values": v_res, "geography.grid_spec": out_grid.spec})
