# (C) Copyright 2023 ECMWF.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.
#

try:
    # NOTE: the `version.py` file must not be present in the git repository
    #   as it is generated by setuptools at install time
    from ._version import __version__
except ImportError:  # pragma: no cover
    # Local copy or not installed with setuptools
    __version__ = "999"


import earthkit.geo.cartography  # noqa: F401
import earthkit.geo.constants  # noqa: F401
import earthkit.geo.coord  # noqa: F401
import earthkit.geo.distance  # noqa: F401
import earthkit.geo.figure  # noqa: F401
import earthkit.geo.gisco  # noqa: F401
import earthkit.geo.grids  # noqa: F401
import earthkit.geo.rotate  # noqa: F401
from earthkit.geo.grids import regrid
from earthkit.geo.utils.caching import CACHE as cache
from earthkit.geo.utils.config import CONFIG as config

__all__ = [
    "cache",
    "config",
    "regrid",
    "__version__",
    "earthkit",
]
